# Simple JSON file DB server
FROM node:22-alpine

WORKDIR /app

# Only need express
RUN npm init -y && npm install express

COPY server/db-server.js ./index.js

# Data directory will be mounted as a volume
RUN mkdir -p /data

EXPOSE 3000

CMD ["node", "index.js"]
